### ISSUE TITLE
InstanceID on vbox not returning properly

### ISSUE THREAD

**Issue by clintonskitson** [emccode/libstorage#121]
This was built from 5e76e6155d5e60892bf96897363b40ff0d23904c.

```
- attachments:
  - devicename: ""
    mountpoint: ""
    instanceid: =5a8952a5-da91-4eaf-baa6-2425adaf9b7c
```

The instanceID on vbox looks to have an extra equals sign.
